# Generated by Django 5.2.6 on 2025-10-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fabricante_id', models.PositiveIntegerField()),
                ('Nombre', models.CharField(max_length=50)),
                ('Pais', models.CharField(max_length=50)),
                ('sitio_web', models.CharField(max_length=50)),
                ('logo_url', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
