# Generated by Django 5.2.6 on 2025-10-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Fabricante',
        ),
    ]
